#!/usr/bin/env python3
"""recursite page engine — a local server that turns editor layouts into pages.

    cd ~/projects/recursite && python3 engine/engine.py
    -> http://<tailnet-ip>:8092/engine/edit.html

Pages live at <repo>/<slug>/ : layout.json (source of truth), index.html (generated),
img/ (pictures the page uses). Optional libraries live at engine/pool/<slug>/
(manifest.json in the foo-picker format + img/) and are git-ignored.

API (all JSON):
  GET  /engine/api/pages                 -> [{slug,title}]
  POST /engine/api/new    {slug,title}   -> creates <slug>/layout.json
  GET  /engine/api/lib?slug=foo          -> {pool:[items…], uploads:[files…]}
  POST /engine/api/upload {slug,name,data}  data = data: URL -> writes <slug>/img/<name>
  POST /engine/api/save   {slug,layout,css,body} -> writes layout.json + index.html
"""
import base64, json, os, re, shutil, sys
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # recursite/
ENGINE = os.path.join(ROOT, "engine")
HOST = os.environ.get("HOST", "100.107.252.39")
PORT = int(os.environ.get("PORT", "8092"))
SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,40}$")
RESERVED = {"engine", "comics", "docs", "usenet", "lascaux", ".git"}

PAGE = """<!DOCTYPE html>
<!-- recursite/%(slug)s/ — generated by engine/engine.py from %(slug)s/layout.json. Edit with engine/edit.html, not by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%(title)s &mdash; the recursite</title>
<link rel="icon" type="image/svg+xml" href="../favicon.svg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Commissioner:wght@400;500;600&family=Piazzolla:ital,wght@0,400;0,500;0,600;1,400&family=Young+Serif&display=swap" rel="stylesheet">
<style>
  body { font-family: "Times New Roman", Times, serif; font-size: 18px; line-height: 1.4; color: #000; background: #ffffcc;
         margin: 3.2em auto 1.4em; padding: 0 1.4em; max-width: 62em; }
  .masthead { text-align: center; }
  h1.welcome { font-size: 2.7em; font-weight: bold; letter-spacing: .03em; color: #101010;
               text-shadow: 1px 1px 0 #fff, 3px 3px 0 #c9b84a; margin: .05em 0 .2em; line-height: 1.08; }
  .rainbow { clear: both; height: 5px; background: linear-gradient(to right,#0033cc,#0099ff,#00cc66,#ffff00,#ff9900,#ff0000); margin: 1.1em 0 .9em; }
  a { color: #0000ee; } a:visited { color: #551a8b; } a:active { color: #ff0000; } a:hover { background: #ffff88; }
  .epigraph { font-style: italic; font-size: .9em; color: #4a4a3a; margin: 0 0 1.1em; }
  .back { font-size: .9em; }
  .foot { margin-top: 2.4em; font-size: .85em; color: #4a4a3a; }
%(css)s
</style>
</head>
<body>
<div class="masthead">
  <h1 class="welcome">%(title)s</h1>
  <div class="rainbow"></div>
</div>
%(epigraph)s
%(body)s

<div class="rainbow"></div>
<p class="back"><a href="../">&larr; Back to the recursite</a></p>
<p class="foot">This primitive HTML site was built by a state-of-the-art language model.</p>
</body>
</html>
"""

def esc(s):
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def page_dir(slug):
    if not SLUG_RE.match(slug) or slug in RESERVED:
        raise ValueError("bad slug")
    return os.path.join(ROOT, slug)

def build(slug, layout, css, body):
    d = page_dir(slug); os.makedirs(os.path.join(d, "img"), exist_ok=True)
    pool = os.path.join(ENGINE, "pool", slug)
    def sub(m):
        rel = m.group(1)
        if rel.startswith("../engine/pool/"):
            src = os.path.join(ROOT, rel[3:])
            if not os.path.isfile(src):
                return m.group(0)
            name = os.path.basename(rel)
            if "/extra/" in rel:
                name = "extra-" + name
            dst = os.path.join(d, "img", name)
            if not os.path.isfile(dst) or os.path.getsize(dst) != os.path.getsize(src):
                shutil.copy2(src, dst)
            return 'src="img/%s"' % name
        return m.group(0)
    body = re.sub(r'src="([^"]+)"', sub, body)
    epi = layout.get("epigraph", "")
    epigraph = '<p class="epigraph">%s</p>' % esc(epi) if epi else ""
    page = PAGE % {"slug": slug, "title": esc(layout.get("title") or slug), "css": css, "body": body, "epigraph": epigraph}
    with open(os.path.join(d, "index.html"), "w", encoding="utf-8") as f:
        f.write(page)
    with open(os.path.join(d, "layout.json"), "w", encoding="utf-8") as f:
        json.dump(layout, f, indent=1, ensure_ascii=False)

def list_pages():
    out = []
    for name in sorted(os.listdir(ROOT)):
        lp = os.path.join(ROOT, name, "layout.json")
        if os.path.isfile(lp) and SLUG_RE.match(name):
            try:
                t = json.load(open(lp)).get("title") or name
            except Exception:
                t = name
            out.append({"slug": name, "title": t})
    return out

class H(SimpleHTTPRequestHandler):
    def __init__(self, *a, **k):
        super().__init__(*a, directory=ROOT, **k)
    def log_message(self, fmt, *args):
        sys.stderr.write("%s %s\n" % (self.address_string(), fmt % args))
    def _json(self, code, obj):
        data = json.dumps(obj).encode()
        self.send_response(code); self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data))); self.end_headers(); self.wfile.write(data)
    def end_headers(self):
        self.send_header("Cache-Control", "no-store"); super().end_headers()
    def do_GET(self):
        u = urlparse(self.path); q = parse_qs(u.query)
        if u.path == "/engine/api/pages":
            return self._json(200, list_pages())
        if u.path == "/engine/api/lib":
            slug = q.get("slug", [""])[0]
            try: d = page_dir(slug)
            except ValueError: return self._json(400, {"error": "bad slug"})
            pool, uploads = [], []
            mp = os.path.join(ENGINE, "pool", slug, "manifest.json")
            if os.path.isfile(mp):
                try: pool = json.load(open(mp)).get("items", [])
                except Exception: pool = []
            ex = os.path.join(ENGINE, "pool", slug, "extra")
            if os.path.isdir(ex):
                pool.insert(0, {"id": "extra", "title": "Extra images", "candidates": [{"type": "image", "file": "extra/" + f, "caption": f} for f in sorted(os.listdir(ex)) if not f.startswith(".")]})
            imgd = os.path.join(d, "img")
            if os.path.isdir(imgd):
                uploads = sorted(f for f in os.listdir(imgd) if not f.startswith("."))
            return self._json(200, {"pool": pool, "uploads": uploads})
        return super().do_GET()
    def do_POST(self):
        n = int(self.headers.get("Content-Length", "0"))
        try:
            req = json.loads(self.rfile.read(n).decode("utf-8"))
            if self.path == "/engine/api/new":
                slug, title = req["slug"].strip(), req.get("title", "").strip() or req["slug"]
                d = page_dir(slug)
                if os.path.exists(os.path.join(d, "layout.json")):
                    return self._json(409, {"error": "page exists"})
                os.makedirs(d, exist_ok=True)
                build(slug, {"title": title, "epigraph": "", "blocks": [], "canvasW": 960, "minH": 600}, "", '<div class="canvas" style="height:600px;max-width:960px;margin:0 auto"></div>')
                return self._json(200, {"ok": True, "slug": slug})
            if self.path == "/engine/api/upload":
                d = page_dir(req["slug"])
                name = re.sub(r"[^A-Za-z0-9._-]", "_", os.path.basename(req["name"]))[:80]
                if not re.search(r"\.(png|jpe?g|gif|webp|svg)$", name, re.I):
                    return self._json(400, {"error": "images only"})
                data = req["data"].split(",", 1)[1]
                os.makedirs(os.path.join(d, "img"), exist_ok=True)
                with open(os.path.join(d, "img", name), "wb") as f:
                    f.write(base64.b64decode(data))
                return self._json(200, {"ok": True, "file": "img/" + name})
            if self.path == "/engine/api/save":
                build(req["slug"], req["layout"], req.get("css", ""), req["body"])
                return self._json(200, {"ok": True, "url": "/%s/" % req["slug"]})
            return self._json(404, {"error": "unknown endpoint"})
        except ValueError as e:
            return self._json(400, {"error": str(e)})
        except Exception as e:
            return self._json(500, {"error": str(e)})

if __name__ == "__main__":
    print("recursite engine: http://%s:%d/engine/edit.html" % (HOST, PORT))
    ThreadingHTTPServer((HOST, PORT), H).serve_forever()
